version: '3.8'
services:
  postgres:
    image: postgres:10.10
    environment:
      POSTGRES_USER: canvas
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus:/prometheus
      - ./prometheus/development.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - alertmanager:/alertmanager
      - ./alertmanager/development.yml:/etc/alertmanager/alertmanager.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/etc/dashboards
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

volumes:
  postgres:
  prometheus:
  grafana:
  alertmanager: